In [2]:
import numpy as np

In [20]:
X = [[1 , 2 , 3 , 4],
    [2.0 , 2 , 1 , 5],
    [1.1 , 2.1 , 0 , 1.1]]

In [21]:
np.random.seed(42)

In [33]:
class Layer_Dence:
    def __init__(self , n_inputs , n_neurons ):
        self.weights = 0.10 * np.random.rand(n_inputs , n_neurons )
        self.biases = np.zeros((1 , n_neurons))

    def forward(self , inputs ):
        self.outputs = np.dot(inputs , self.weights ) + self.biases


In [34]:
layer1 = Layer_Dence(4 , 5)
layer2 = Layer_Dence(5 , 4 )

In [35]:
layer1.forward(X)
print(f"layer - 1  :  {layer1.outputs}")

layer - 1  :  [[0.48851104 0.51555284 0.53608315 0.69607642 0.51191065]
 [0.52084972 0.62731683 0.40023622 0.67456531 0.52992077]
 [0.15166924 0.24458949 0.2137676  0.20217188 0.17532574]]


In [37]:
layer2.forward(layer1.outputs)
print(f" layer 2 : {layer2.outputs}")

 layer 2 : [[0.08646929 0.1526639  0.16433281 0.13390215]
 [0.09221    0.15393682 0.16745985 0.14191559]
 [0.02948913 0.05410704 0.05919216 0.05104176]]
